README.md, fanfiction_backend.py, fanfiction_bot.py
Minor reformatting and added argparser
=> Reformatting and argparser

fanfiction_backend.py, fanfiction_bot.py
=> Minor reformats

ffn_bot/fanfiction_parser.py
- Use generators to save memory.
- Use string joins to minimize overhead
=> Minor improvements

ffn_bot/reddit_bot.py
Warning: Untested but should work.
Implements #9
=> Make pause function skippable. Implements #9

ffn_bot/fanfiction_parser.py
Requires Python>=3.2 otherwise it will fallback to uncached bahaviour.
=> Implement a cache

ffn_bot/fanfiction_parser.py
=> Yield links directly without googling

ffn_bot/fanfiction_parser.py
Doesn't work, unlike the previous one:
'''
Parsing submissions on SUBREDDIT  tusingtestfield
Parsing comment  cs56avu  in submission  39p3e7
FINDING:  {'ffn': ['Harry Potter and the Methods of Rationality\u200e\u200e']}
FFN requests:  ['Harry Potter and the Methods of Rationality\u200e\u200e']
ERROR:root:MAIN: AN EXCEPTION HAS OCCURED!
ERROR:root:!! Traceback (most recent call last):
!!   File "c:\Google Drive\Programming\reddit-ffn-bot\ffn_bot\reddit_bot.py", line 29, in __main__
initialize()
!!   File "c:\Google Drive\Programming\reddit-ffn-bot\ffn_bot\reddit_bot.py", line 45, in initialize
parse_submissions(r.get_subreddit(SUBREDDIT))
!!   File "c:\Google Drive\Programming\reddit-ffn-bot\ffn_bot\reddit_bot.py", line 128, in parse_submissions
make_reply(comment, comment.id)
!!   File …
=> Revert "Allow non-ascii characters in story name"

requirements.txt
Better for those who want to help.
=> Add list of pip-dependencies

ffn_bot/ao3.py, ffn_bot/fanfiction_parser.py, ffn_bot/reddit_bot.py, ffn_bot/site.py
Yay...
Usage: `linkao3(Crossovers that should not be)`
=> Added support for AO3

ffn_bot/fanfiction_parser.py
=> Moved everything in fanfiction_parser to its respective classes.

ffn_bot/ao3.py
=> Fixed multiline summary bug on ao3

ffn_bot/ao3.py
See #33 #32 
I didn't notice until it was too late.
=> Fixed author link

ffn_bot/ao3.py, ffn_bot/fanfiction_parser.py, ffn_bot/site.py
So we don't have to rewrite the reply anymore.
=> Both __str__ functions are now in one place.

ffn_bot/ao3.py
Needed to recreate request since I accidentally manage to close the reqiest by deleting by branch.
See #36
=> Fixed non matching ao3 url on parsing

ffn_bot/ao3.py, ffn_bot/fanfiction_parser.py, ffn_bot/reddit_bot.py
Don't build the story string in from_requests. Instead do it in formulate_reply
=> Delay building the response string

ffn_bot/ao3.py, ffn_bot/cache.py, ffn_bot/fanfiction_parser.py
I think it is better to use a cache for both search requests and downloads.
BTW: This works. At least with the tests I did.
=> Implementation of a central cache

ffn_bot/reddit_bot.py
Unfortunately untested though.
=> Added support for submission text.

ffn_bot/bot_tools.py
We pass a function (defaults to int-constructor) for converting strings to ints. No need to hard-code it.
=> Use the converter-function.

ffn_bot/fanfiction_parser.py
- FFN: Fandom (and Crossovers)
- FP: Text-Genre
Resolves #23
=> Added information for ffn and fp.

ffn_bot/ao3.py, ffn_bot/site.py, requirements.txt
Note the additional library needed for this: cssselect
=> Added fandom-list for ao3

__main__.py, ffn_bot/reddit_bot.py
The issue with __main__ is that it is only important for module names
=> Better naming for the entry-points

ffn_bot/ffa.py
Warning: Written on a on-screen keyboard
=> Cache Page-Load

ffn_bot/reddit_bot.py
Implements #55 
Untested though...
=> Implemented Semicolons

ffn_bot/ao3.py
Untested but should work. (Seriously)
=> Fixes AO3 bug on mature works.

ffn_bot/cache.py
In preparation to add other sites.
Conflicts with #52 
Resolve merge conflict by replacing the conflict at line 57 with
def get_page(self, page, throttle=0, **kwargs)
=> Add support to add kwargs to cache.get_page

ffn_bot/ao3.py, ffn_bot/fanfiction_parser.py, ffn_bot/reddit_bot.py, ffn_bot/site.py
- Opt in with ffnbot!directlinks
- HPFanfictionArchive not supported due to bug in Link-Regex
Fixes #6 
Fixes #63 
Needs #62 to fix edge case when linkxxx(<link>) is used.
=> Added support for direct links

ffn_bot/reddit_bot.py
Now someone can use "ffnbot!submissionlink" to trigger the bot
to fetch the metadata from the submission link.
(Useful on promotion submissions)
Untested as I have never started the bot myself, I only ever triggered
the formulate_reply routine
=> Added flag "submissionlink"

ffn_bot/ffa.py
And thus I was able to implement direct links in FFA.
=> Fixed bug in FFAs link-regex

ffn_bot/site.py
=> Basic escape for metadata keys and values

ffn_bot/fetchers/ffn.py
Changed URL to point at the new host. Fixes #92
=> Changed p0ody URL to new address

ffn_bot/fetchers/ffn.py
p0ody-files relocated to http://ff2ebook.com/old/mobile/index.php so new downloader
Everything seems to be working with the new URL, so give it a go!
=> changed p0ody files download url

ffn_bot/fetchers/ao3.py
Simplest fix possible for issue filed at
https://github.com/tusing/reddit-ffn-bot/issues/96.
=> Add missing domain to Ao3 author link

google/__init__.py
=> Cross-platform home directory discovery
